### ISSUE TITLE
Rendering Issues

### ISSUE THREAD

**Issue by gityman** [SonicOnset/SonicOnset#3]
My Computer doesn't have vulkan compatibility. but the engine the game is using (godot) allows for it to run with opengl3 using shortcuts or terminal. which my computer supports. but opengl3 causes everything in the test area (apart from the hud) to be gone. so opengl3 compatibility is a must to add additional support for the game

-love. gityman

**Comment by cuckydev** [comment]
Please read the issues FAQ
https://github.com/SonicOnset/SonicOnset/issues/2

**Comment by gityman** [comment]
> Please read the issues FAQ #2

well now that's just bullshit

**Comment by cuckydev** [comment]
> > Please read the issues FAQ #2
> 
> well now that's just bullshit

No it's not
